### ISSUE TITLE
500 error when posting a reply to previous reply.

### ISSUE THREAD

**Issue by b-bayport** [theatl-social/mastodon#9]
### Steps to reproduce the problem

1. Open post that is a reply to previous post https://beta.theatl.social/@bayport4beta/112700534265055537 
2. Type another reply
3. Press post results
![IMG_5900](https://github.com/theatl-social/mastodon/assets/121366909/f8d04856-9b11-477a-87d0-4005418f718b)

...

### Expected behaviour

Reply should be posted as a thread

### Actual behaviour

500 error toast popup

### Mastodon instance

Beta.theATL.social

### Mastodon version

v4.2.9-theatlsocial-20240612.1

### Browser name and version

DuckDuckGo v7.123.0.2

### Operating system

iOS 17.5.1

**Comment by mikehikes** [comment]
Thank you! The underlying issue has been fixed in `app/controllers/api/v1/statuses_controller.rb`, line 79

**Comment by adam-lab** [comment]
I'm seeing this now. I tried to add a third comment to my thread about images, and got this 500 error.
